name: Shop Hilfe
main: de.mineterra.shop.shop
version: 1.1
author: mineterra.de
commands:
     shop:
        description: Zeigt dir das Hilfe Menue an.
        usage: /<command> [hilfe] [paystand] [payhaus]